### ISSUE TITLE
Link is not working 

### ISSUE THREAD

**Issue by shohan4556** [LisaDziuba/Marketing-for-Engineers#12]
this link from LinkedIn section is not working [**want to effectively raise your linkedin profile follow**](https://themission.co/want-to-effectively-raise-your-linkedin-profile-follow-these-tips-36679852f058)

**Comment by LisaDziuba** [comment]
thanks for your report! 
I will delete it now and will set up a bot for fixing such issues :)

Thank you again! Lisa

**Comment by LisaDziuba** [comment]
@shohan4556 I deleted the expired link and put the new one. It looked like the Medium collection owners just changed their blog name and the link automatically was changed too :(
