### ISSUE TITLE
Link for "How to Get Press Coverage for Your App" is dead

### ISSUE THREAD

**Issue by vincent-pradeilles** [LisaDziuba/Marketing-for-Engineers#33]
Hi,

I wanted to let you know that the link for the article "How to Get Press Coverage for Your App: practical guide from Dan Counsell, indie developer & agency founder." no longer works.

**Comment by LisaDziuba** [comment]
thanks for reporting @vincent-pradeilles !
the author transferred this guide to a new blog. I will change a link and will set up automation to check all my links from time to time :)
